x <-
c("item_id", "store_id", "sell_price", "prices_diff", "prices_rel_diff", 
"prices_cumrel", "prices_roll_sd7", "prices_roll_mean7", "price_diff_from_previous_mean", 
"diff_from_mean", "best_price", "day_year", "wday", "quarter", 
"month", "year", "snap_CA", "snap_TX", "snap_WI", "day_month", 
"day_quarter", "week_month", "week_quarter", "week_year", "month_quarter", 
"quarter_semester", "semester", "wday_S1-7", "wday_C1-7", "wday_S2-7", 
"wday_C2-7", "wday_S3-7", "wday_C3-7", "month_S1-12", "month_C1-12", 
"month_S2-12", "month_C2-12", "month_S3-12", "month_C3-12", "quarter_S1-4", 
"quarter_C1-4", "quarter_C2-4", "semester_v2", "event_name", 
"event_type", "rbf_d1", "rbf_d2", "rbf_d3", "rbf_d4", "rbf_d5", 
"rbf_d6", "rbf_d7", "rbf_m1", "rbf_m2", "rbf_m3", "rbf_m4", "rbf_m5", 
"rbf_m6", "rbf_m7", "rbf_m8", "rbf_m9", "rbf_m10", "rbf_m11", 
"rbf_m12", "dept_id", "cat_id", "state_id", "demand", "lag_t7", 
"lag_t14", "lag_t21", "lag_t28", "last_month_mean", "rolling_mean_lag7_t7", 
"rolling_mean_lag7_t30", "rolling_mean_lag7_t60", "rolling_mean_lag7_t90", 
"rolling_mean_lag7_t180", "rolling_mean_lag28_t7", "rolling_mean_lag28_t30", 
"rolling_mean_lag28_t60", "rolling_mean_lag28_t90", "rolling_mean_lag28_t180", 
"rolling_sd_lag7_t7", "rolling_sd_lag7_t30", "rolling_sd_lag28_t7", 
"rolling_sd_lag28_t30", "snap")
